insert into competitions (name, type, prize_money, reputation) values
  ('UEFA Champions League', 'continental', 85000000, 98),
  ('UEFA Europa League', 'continental', 42000000, 90),
  ('UEFA Conference League', 'continental', 26000000, 84),
  ('FIFA World Cup', 'international', 120000000, 99),
  ('UEFA Euros', 'international', 70000000, 96),
  ('Copa America', 'international', 50000000, 94),
  ('AFCON', 'international', 30000000, 88),
  ('CONCACAF Gold Cup', 'international', 24000000, 82),
  ('Domestic Cup', 'domestic', 12000000, 78)
on conflict (name) do nothing;

create temporary table if not exists _league_seed (
  name text not null,
  country text not null,
  reputation integer not null,
  tier integer not null
) on commit drop;

truncate _league_seed;

insert into _league_seed (name, country, reputation, tier) values
  ('Premier League', 'England', 95, 1),
  ('Championship', 'England', 84, 2),
  ('League One', 'England', 75, 3),
  ('La Liga', 'Spain', 94, 1),
  ('La Liga 2', 'Spain', 82, 2),
  ('Primera RFEF', 'Spain', 72, 3),
  ('Serie A', 'Italy', 93, 1),
  ('Serie B', 'Italy', 81, 2),
  ('Bundesliga', 'Germany', 92, 1),
  ('2. Bundesliga', 'Germany', 80, 2),
  ('Ligue 1', 'France', 90, 1),
  ('Ligue 2', 'France', 78, 2),
  ('Eredivisie', 'Netherlands', 88, 1),
  ('Primeira Liga', 'Portugal', 86, 1),
  ('Belgian Pro League', 'Belgium', 83, 1),
  ('Super Lig', 'Turkey', 82, 1),
  ('Brasileirao', 'Brazil', 91, 1),
  ('Serie B Brasil', 'Brazil', 78, 2),
  ('Liga Profesional', 'Argentina', 89, 1),
  ('Primera Nacional', 'Argentina', 76, 2),
  ('MLS', 'United States', 80, 1),
  ('Liga MX', 'Mexico', 84, 1),
  ('Scottish Premiership', 'Scotland', 79, 1),
  ('Scottish Championship', 'Scotland', 70, 2),
  ('Saudi Pro League', 'Saudi Arabia', 81, 1),
  ('J1 League', 'Japan', 80, 1),
  ('J2 League', 'Japan', 72, 2),
  ('K League 1', 'South Korea', 79, 1),
  ('A-League', 'Australia', 74, 1),
  ('Danish Superliga', 'Denmark', 78, 1),
  ('Swiss Super League', 'Switzerland', 78, 1),
  ('Austrian Bundesliga', 'Austria', 77, 1),
  ('Greek Super League', 'Greece', 76, 1),
  ('Polish Ekstraklasa', 'Poland', 75, 1),
  ('Czech First League', 'Czech Republic', 74, 1),
  ('Ukrainian Premier League', 'Ukraine', 74, 1),
  ('Romanian SuperLiga', 'Romania', 72, 1),
  ('Serbian SuperLiga', 'Serbia', 73, 1),
  ('Croatian League', 'Croatia', 73, 1),
  ('Norwegian Eliteserien', 'Norway', 74, 1),
  ('Swedish Allsvenskan', 'Sweden', 75, 1),
  ('Finnish Veikkausliiga', 'Finland', 70, 1),
  ('Chinese Super League', 'China', 76, 1),
  ('Indian Super League', 'India', 68, 1),
  ('South African Premiership', 'South Africa', 71, 1),
  ('Egyptian Premier League', 'Egypt', 73, 1),
  ('Moroccan Botola', 'Morocco', 71, 1),
  ('Colombian Primera A', 'Colombia', 77, 1),
  ('Chilean Primera Division', 'Chile', 75, 1),
  ('Peruvian Liga 1', 'Peru', 72, 1);

insert into leagues (name, country, reputation, tier)
select ls.name, ls.country, ls.reputation, ls.tier
from _league_seed ls
where not exists (
  select 1
  from leagues l
  where l.name = ls.name and l.country = ls.country
);

create temporary table if not exists _club_seed (
  league_name text not null,
  club_order integer not null,
  club_name text not null
) on commit drop;

truncate _club_seed;

insert into _club_seed (league_name, club_order, club_name) values
('Premier League', 1, 'Arsenal'),
  ('Premier League', 2, 'Aston Villa'),
  ('Premier League', 3, 'Bournemouth'),
  ('Premier League', 4, 'Brentford'),
  ('Premier League', 5, 'Brighton & Hove Albion'),
  ('Premier League', 6, 'Chelsea'),
  ('Premier League', 7, 'Crystal Palace'),
  ('Premier League', 8, 'Everton'),
  ('Premier League', 9, 'Fulham'),
  ('Premier League', 10, 'Ipswich Town'),
  ('Premier League', 11, 'Leicester City'),
  ('Premier League', 12, 'Liverpool'),
  ('Premier League', 13, 'Manchester City'),
  ('Premier League', 14, 'Manchester United'),
  ('Premier League', 15, 'Newcastle United'),
  ('Premier League', 16, 'Nottingham Forest'),
  ('Premier League', 17, 'Southampton'),
  ('Premier League', 18, 'Tottenham Hotspur'),
  ('Premier League', 19, 'West Ham United'),
  ('Premier League', 20, 'Wolverhampton Wanderers'),
  ('Championship', 1, 'Blackburn Rovers'),
  ('Championship', 2, 'Bristol City'),
  ('Championship', 3, 'Burnley'),
  ('Championship', 4, 'Cardiff City'),
  ('Championship', 5, 'Coventry City'),
  ('Championship', 6, 'Derby County'),
  ('Championship', 7, 'Hull City'),
  ('Championship', 8, 'Leeds United'),
  ('Championship', 9, 'Luton Town'),
  ('Championship', 10, 'Middlesbrough'),
  ('Championship', 11, 'Millwall'),
  ('Championship', 12, 'Norwich City'),
  ('Championship', 13, 'Oxford United'),
  ('Championship', 14, 'Plymouth Argyle'),
  ('Championship', 15, 'Portsmouth'),
  ('Championship', 16, 'Preston North End'),
  ('Championship', 17, 'Queens Park Rangers'),
  ('Championship', 18, 'Sheffield United'),
  ('Championship', 19, 'Sheffield Wednesday'),
  ('Championship', 20, 'Stoke City'),
  ('Championship', 21, 'Sunderland'),
  ('Championship', 22, 'Swansea City'),
  ('Championship', 23, 'Watford'),
  ('Championship', 24, 'West Bromwich Albion'),
  ('League One', 1, 'Barnsley'),
  ('League One', 2, 'Blackpool'),
  ('League One', 3, 'Bolton Wanderers'),
  ('League One', 4, 'Bristol Rovers'),
  ('League One', 5, 'Burton Albion'),
  ('League One', 6, 'Cambridge United'),
  ('League One', 7, 'Charlton Athletic'),
  ('League One', 8, 'Exeter City'),
  ('League One', 9, 'Huddersfield Town'),
  ('League One', 10, 'Leyton Orient'),
  ('League One', 11, 'Lincoln City'),
  ('League One', 12, 'Mansfield Town'),
  ('League One', 13, 'Northampton Town'),
  ('League One', 14, 'Peterborough United'),
  ('League One', 15, 'Reading'),
  ('League One', 16, 'Rotherham United'),
  ('League One', 17, 'Shrewsbury Town'),
  ('League One', 18, 'Stevenage'),
  ('League One', 19, 'Stockport County'),
  ('League One', 20, 'Wigan Athletic'),
  ('League One', 21, 'Wrexham'),
  ('League One', 22, 'Wycombe Wanderers'),
  ('League One', 23, 'Birmingham City'),
  ('League One', 24, 'Crawley Town'),
  ('La Liga', 1, 'Alaves'),
  ('La Liga', 2, 'Athletic Club'),
  ('La Liga', 3, 'Atletico Madrid'),
  ('La Liga', 4, 'Barcelona'),
  ('La Liga', 5, 'Celta Vigo'),
  ('La Liga', 6, 'Espanyol'),
  ('La Liga', 7, 'Getafe'),
  ('La Liga', 8, 'Girona'),
  ('La Liga', 9, 'Las Palmas'),
  ('La Liga', 10, 'Leganes'),
  ('La Liga', 11, 'Mallorca'),
  ('La Liga', 12, 'Osasuna'),
  ('La Liga', 13, 'Rayo Vallecano'),
  ('La Liga', 14, 'Real Betis'),
  ('La Liga', 15, 'Real Madrid'),
  ('La Liga', 16, 'Real Sociedad'),
  ('La Liga', 17, 'Sevilla'),
  ('La Liga', 18, 'Valencia'),
  ('La Liga', 19, 'Valladolid'),
  ('La Liga', 20, 'Villarreal'),
  ('La Liga 2', 1, 'Albacete'),
  ('La Liga 2', 2, 'Almeria'),
  ('La Liga 2', 3, 'Burgos'),
  ('La Liga 2', 4, 'Cadiz'),
  ('La Liga 2', 5, 'Cartagena'),
  ('La Liga 2', 6, 'Castellon'),
  ('La Liga 2', 7, 'Cordoba'),
  ('La Liga 2', 8, 'Deportivo La Coruna'),
  ('La Liga 2', 9, 'Eibar'),
  ('La Liga 2', 10, 'Elche'),
  ('La Liga 2', 11, 'Eldense'),
  ('La Liga 2', 12, 'Granada'),
  ('La Liga 2', 13, 'Huesca'),
  ('La Liga 2', 14, 'Levante'),
  ('La Liga 2', 15, 'Malaga'),
  ('La Liga 2', 16, 'Mirandes'),
  ('La Liga 2', 17, 'Oviedo'),
  ('La Liga 2', 18, 'Racing Santander'),
  ('La Liga 2', 19, 'Sporting Gijon'),
  ('La Liga 2', 20, 'Tenerife'),
  ('La Liga 2', 21, 'Real Zaragoza'),
  ('La Liga 2', 22, 'Alcorcon'),
  ('Primera RFEF', 1, 'Algeciras'),
  ('Primera RFEF', 2, 'Antequera'),
  ('Primera RFEF', 3, 'Arenteiro'),
  ('Primera RFEF', 4, 'Celta Fortuna'),
  ('Primera RFEF', 5, 'Cultural Leonesa'),
  ('Primera RFEF', 6, 'Gimnastic Tarragona'),
  ('Primera RFEF', 7, 'Ibiza'),
  ('Primera RFEF', 8, 'Lugo'),
  ('Primera RFEF', 9, 'Ponferradina'),
  ('Primera RFEF', 10, 'Real Union'),
  ('Primera RFEF', 11, 'Sabadell'),
  ('Primera RFEF', 12, 'Sestao River'),
  ('Primera RFEF', 13, 'Tarazona'),
  ('Primera RFEF', 14, 'Unionistas'),
  ('Primera RFEF', 15, 'Barcelona Atletic'),
  ('Primera RFEF', 16, 'Athletic Bilbao B'),
  ('Primera RFEF', 17, 'Real Madrid Castilla'),
  ('Primera RFEF', 18, 'Murcia'),
  ('Primera RFEF', 19, 'Cordoba B'),
  ('Primera RFEF', 20, 'Merida'),
  ('Serie A', 1, 'Atalanta'),
  ('Serie A', 2, 'Bologna'),
  ('Serie A', 3, 'Cagliari'),
  ('Serie A', 4, 'Como'),
  ('Serie A', 5, 'Empoli'),
  ('Serie A', 6, 'Fiorentina'),
  ('Serie A', 7, 'Genoa'),
  ('Serie A', 8, 'Hellas Verona'),
  ('Serie A', 9, 'Inter Milan'),
  ('Serie A', 10, 'Juventus'),
  ('Serie A', 11, 'Lazio'),
  ('Serie A', 12, 'Lecce'),
  ('Serie A', 13, 'Milan'),
  ('Serie A', 14, 'Monza'),
  ('Serie A', 15, 'Napoli'),
  ('Serie A', 16, 'Parma'),
  ('Serie A', 17, 'Roma'),
  ('Serie A', 18, 'Torino'),
  ('Serie A', 19, 'Udinese'),
  ('Serie A', 20, 'Venezia'),
  ('Serie B', 1, 'Bari'),
  ('Serie B', 2, 'Brescia'),
  ('Serie B', 3, 'Carrarese'),
  ('Serie B', 4, 'Catanzaro'),
  ('Serie B', 5, 'Cesena'),
  ('Serie B', 6, 'Cittadella'),
  ('Serie B', 7, 'Cosenza'),
  ('Serie B', 8, 'Cremonese'),
  ('Serie B', 9, 'Frosinone'),
  ('Serie B', 10, 'Juve Stabia'),
  ('Serie B', 11, 'Mantova'),
  ('Serie B', 12, 'Modena'),
  ('Serie B', 13, 'Palermo'),
  ('Serie B', 14, 'Pisa'),
  ('Serie B', 15, 'Reggiana'),
  ('Serie B', 16, 'Salernitana'),
  ('Serie B', 17, 'Sampdoria'),
  ('Serie B', 18, 'Sassuolo'),
  ('Serie B', 19, 'Spezia'),
  ('Serie B', 20, 'Sudtirol'),
  ('Bundesliga', 1, 'Augsburg'),
  ('Bundesliga', 2, 'Bayer Leverkusen'),
  ('Bundesliga', 3, 'Bayern Munich'),
  ('Bundesliga', 4, 'Bochum'),
  ('Bundesliga', 5, 'Borussia Dortmund'),
  ('Bundesliga', 6, 'Borussia Monchengladbach'),
  ('Bundesliga', 7, 'Eintracht Frankfurt'),
  ('Bundesliga', 8, 'Freiburg'),
  ('Bundesliga', 9, 'Heidenheim'),
  ('Bundesliga', 10, 'Holstein Kiel'),
  ('Bundesliga', 11, 'Hoffenheim'),
  ('Bundesliga', 12, 'Mainz 05'),
  ('Bundesliga', 13, 'RB Leipzig'),
  ('Bundesliga', 14, 'St. Pauli'),
  ('Bundesliga', 15, 'Stuttgart'),
  ('Bundesliga', 16, 'Union Berlin'),
  ('Bundesliga', 17, 'Werder Bremen'),
  ('Bundesliga', 18, 'Wolfsburg'),
  ('2. Bundesliga', 1, 'Darmstadt 98'),
  ('2. Bundesliga', 2, 'Eintracht Braunschweig'),
  ('2. Bundesliga', 3, 'Fortuna Dusseldorf'),
  ('2. Bundesliga', 4, 'Greuther Furth'),
  ('2. Bundesliga', 5, 'Hamburger SV'),
  ('2. Bundesliga', 6, 'Hannover 96'),
  ('2. Bundesliga', 7, 'Hertha BSC'),
  ('2. Bundesliga', 8, 'Jahn Regensburg'),
  ('2. Bundesliga', 9, 'Karlsruher SC'),
  ('2. Bundesliga', 10, 'Koln'),
  ('2. Bundesliga', 11, 'Magdeburg'),
  ('2. Bundesliga', 12, 'Nurnberg'),
  ('2. Bundesliga', 13, 'Paderborn'),
  ('2. Bundesliga', 14, 'Schalke 04'),
  ('2. Bundesliga', 15, 'Ulm'),
  ('2. Bundesliga', 16, 'Elversberg'),
  ('2. Bundesliga', 17, 'Kaiserslautern'),
  ('2. Bundesliga', 18, 'Preussen Munster'),
  ('Ligue 1', 1, 'Angers'),
  ('Ligue 1', 2, 'Auxerre'),
  ('Ligue 1', 3, 'Brest'),
  ('Ligue 1', 4, 'Le Havre'),
  ('Ligue 1', 5, 'Lens'),
  ('Ligue 1', 6, 'Lille'),
  ('Ligue 1', 7, 'Lyon'),
  ('Ligue 1', 8, 'Marseille'),
  ('Ligue 1', 9, 'Monaco'),
  ('Ligue 1', 10, 'Montpellier'),
  ('Ligue 1', 11, 'Nantes'),
  ('Ligue 1', 12, 'Nice'),
  ('Ligue 1', 13, 'Paris Saint-Germain'),
  ('Ligue 1', 14, 'Reims'),
  ('Ligue 1', 15, 'Rennes'),
  ('Ligue 1', 16, 'Saint-Etienne'),
  ('Ligue 1', 17, 'Strasbourg'),
  ('Ligue 1', 18, 'Toulouse'),
  ('Ligue 2', 1, 'Ajaccio'),
  ('Ligue 2', 2, 'Amiens'),
  ('Ligue 2', 3, 'Annecy'),
  ('Ligue 2', 4, 'Bastia'),
  ('Ligue 2', 5, 'Caen'),
  ('Ligue 2', 6, 'Clermont'),
  ('Ligue 2', 7, 'Dunkerque'),
  ('Ligue 2', 8, 'Grenoble'),
  ('Ligue 2', 9, 'Guingamp'),
  ('Ligue 2', 10, 'Laval'),
  ('Ligue 2', 11, 'Lorient'),
  ('Ligue 2', 12, 'Metz'),
  ('Ligue 2', 13, 'Pau'),
  ('Ligue 2', 14, 'Red Star'),
  ('Ligue 2', 15, 'Rodez'),
  ('Ligue 2', 16, 'Troyes'),
  ('Ligue 2', 17, 'Paris FC'),
  ('Ligue 2', 18, 'Martigues'),
  ('Eredivisie', 1, 'Ajax'),
  ('Eredivisie', 2, 'Almere City'),
  ('Eredivisie', 3, 'AZ Alkmaar'),
  ('Eredivisie', 4, 'Feyenoord'),
  ('Eredivisie', 5, 'Fortuna Sittard'),
  ('Eredivisie', 6, 'Go Ahead Eagles'),
  ('Eredivisie', 7, 'Groningen'),
  ('Eredivisie', 8, 'Heerenveen'),
  ('Eredivisie', 9, 'Heracles Almelo'),
  ('Eredivisie', 10, 'NAC Breda'),
  ('Eredivisie', 11, 'NEC Nijmegen'),
  ('Eredivisie', 12, 'PEC Zwolle'),
  ('Eredivisie', 13, 'PSV'),
  ('Eredivisie', 14, 'RKC Waalwijk'),
  ('Eredivisie', 15, 'Sparta Rotterdam'),
  ('Eredivisie', 16, 'Twente'),
  ('Eredivisie', 17, 'Utrecht'),
  ('Eredivisie', 18, 'Willem II'),
  ('Primeira Liga', 1, 'Arouca'),
  ('Primeira Liga', 2, 'AVS'),
  ('Primeira Liga', 3, 'Benfica'),
  ('Primeira Liga', 4, 'Boavista'),
  ('Primeira Liga', 5, 'Braga'),
  ('Primeira Liga', 6, 'Casa Pia'),
  ('Primeira Liga', 7, 'Estoril'),
  ('Primeira Liga', 8, 'Estrela Amadora'),
  ('Primeira Liga', 9, 'Famalicao'),
  ('Primeira Liga', 10, 'Farense'),
  ('Primeira Liga', 11, 'Gil Vicente'),
  ('Primeira Liga', 12, 'Moreirense'),
  ('Primeira Liga', 13, 'Nacional'),
  ('Primeira Liga', 14, 'Porto'),
  ('Primeira Liga', 15, 'Rio Ave'),
  ('Primeira Liga', 16, 'Santa Clara'),
  ('Primeira Liga', 17, 'Sporting CP'),
  ('Primeira Liga', 18, 'Vitoria Guimaraes'),
  ('Belgian Pro League', 1, 'Anderlecht'),
  ('Belgian Pro League', 2, 'Antwerp'),
  ('Belgian Pro League', 3, 'Beerschot'),
  ('Belgian Pro League', 4, 'Cercle Brugge'),
  ('Belgian Pro League', 5, 'Charleroi'),
  ('Belgian Pro League', 6, 'Club Brugge'),
  ('Belgian Pro League', 7, 'Dender'),
  ('Belgian Pro League', 8, 'Genk'),
  ('Belgian Pro League', 9, 'Gent'),
  ('Belgian Pro League', 10, 'Kortrijk'),
  ('Belgian Pro League', 11, 'Leuven'),
  ('Belgian Pro League', 12, 'Mechelen'),
  ('Belgian Pro League', 13, 'Sint-Truiden'),
  ('Belgian Pro League', 14, 'Standard Liege'),
  ('Belgian Pro League', 15, 'Union Saint-Gilloise'),
  ('Belgian Pro League', 16, 'Westerlo'),
  ('Super Lig', 1, 'Adana Demirspor'),
  ('Super Lig', 2, 'Alanyaspor'),
  ('Super Lig', 3, 'Antalyaspor'),
  ('Super Lig', 4, 'Besiktas'),
  ('Super Lig', 5, 'Bodrum FK'),
  ('Super Lig', 6, 'Caykur Rizespor'),
  ('Super Lig', 7, 'Eyupspor'),
  ('Super Lig', 8, 'Fenerbahce'),
  ('Super Lig', 9, 'Galatasaray'),
  ('Super Lig', 10, 'Gaziantep'),
  ('Super Lig', 11, 'Goztepe'),
  ('Super Lig', 12, 'Hatayspor'),
  ('Super Lig', 13, 'Kasimpasa'),
  ('Super Lig', 14, 'Kayserispor'),
  ('Super Lig', 15, 'Konyaspor'),
  ('Super Lig', 16, 'Samsunspor'),
  ('Super Lig', 17, 'Sivasspor'),
  ('Super Lig', 18, 'Trabzonspor'),
  ('Super Lig', 19, 'Basaksehir'),
  ('Super Lig', 20, 'Ankaragucu'),
  ('Brasileirao', 1, 'Atletico Goianiense'),
  ('Brasileirao', 2, 'Atletico Mineiro'),
  ('Brasileirao', 3, 'Bahia'),
  ('Brasileirao', 4, 'Botafogo'),
  ('Brasileirao', 5, 'Bragantino'),
  ('Brasileirao', 6, 'Corinthians'),
  ('Brasileirao', 7, 'Criciuma'),
  ('Brasileirao', 8, 'Cruzeiro'),
  ('Brasileirao', 9, 'Cuiaba'),
  ('Brasileirao', 10, 'Flamengo'),
  ('Brasileirao', 11, 'Fluminense'),
  ('Brasileirao', 12, 'Fortaleza'),
  ('Brasileirao', 13, 'Gremio'),
  ('Brasileirao', 14, 'Internacional'),
  ('Brasileirao', 15, 'Juventude'),
  ('Brasileirao', 16, 'Palmeiras'),
  ('Brasileirao', 17, 'Sao Paulo'),
  ('Brasileirao', 18, 'Vasco da Gama'),
  ('Brasileirao', 19, 'Vitoria'),
  ('Brasileirao', 20, 'Athletico Paranaense'),
  ('Serie B Brasil', 1, 'Amazonas'),
  ('Serie B Brasil', 2, 'America Mineiro'),
  ('Serie B Brasil', 3, 'Avai'),
  ('Serie B Brasil', 4, 'Botafogo SP'),
  ('Serie B Brasil', 5, 'Brusque'),
  ('Serie B Brasil', 6, 'CRB'),
  ('Serie B Brasil', 7, 'Ceara'),
  ('Serie B Brasil', 8, 'Chapecoense'),
  ('Serie B Brasil', 9, 'Coritiba'),
  ('Serie B Brasil', 10, 'Goias'),
  ('Serie B Brasil', 11, 'Guarani'),
  ('Serie B Brasil', 12, 'Ituano'),
  ('Serie B Brasil', 13, 'Mirassol'),
  ('Serie B Brasil', 14, 'Novorizontino'),
  ('Serie B Brasil', 15, 'Operario'),
  ('Serie B Brasil', 16, 'Paysandu'),
  ('Serie B Brasil', 17, 'Ponte Preta'),
  ('Serie B Brasil', 18, 'Santos'),
  ('Serie B Brasil', 19, 'Sport Recife'),
  ('Serie B Brasil', 20, 'Vila Nova'),
  ('Liga Profesional', 1, 'Argentinos Juniors'),
  ('Liga Profesional', 2, 'Banfield'),
  ('Liga Profesional', 3, 'Barracas Central'),
  ('Liga Profesional', 4, 'Belgrano'),
  ('Liga Profesional', 5, 'Boca Juniors'),
  ('Liga Profesional', 6, 'Central Cordoba'),
  ('Liga Profesional', 7, 'Defensa y Justicia'),
  ('Liga Profesional', 8, 'Estudiantes'),
  ('Liga Profesional', 9, 'Gimnasia La Plata'),
  ('Liga Profesional', 10, 'Godoy Cruz'),
  ('Liga Profesional', 11, 'Huracan'),
  ('Liga Profesional', 12, 'Independiente'),
  ('Liga Profesional', 13, 'Instituto'),
  ('Liga Profesional', 14, 'Lanus'),
  ('Liga Profesional', 15, 'Newell''s Old Boys'),
  ('Liga Profesional', 16, 'Racing Club'),
  ('Liga Profesional', 17, 'River Plate'),
  ('Liga Profesional', 18, 'Rosario Central'),
  ('Liga Profesional', 19, 'San Lorenzo'),
  ('Liga Profesional', 20, 'Talleres'),
  ('Primera Nacional', 1, 'Agropecuario'),
  ('Primera Nacional', 2, 'Almagro'),
  ('Primera Nacional', 3, 'Almirante Brown'),
  ('Primera Nacional', 4, 'Atlanta'),
  ('Primera Nacional', 5, 'Brown de Adrogue'),
  ('Primera Nacional', 6, 'Chacarita Juniors'),
  ('Primera Nacional', 7, 'Deportivo Madryn'),
  ('Primera Nacional', 8, 'Deportivo Moron'),
  ('Primera Nacional', 9, 'Estudiantes Rio Cuarto'),
  ('Primera Nacional', 10, 'Ferro Carril Oeste'),
  ('Primera Nacional', 11, 'Gimnasia y Tiro'),
  ('Primera Nacional', 12, 'Nueva Chicago'),
  ('Primera Nacional', 13, 'Patronato'),
  ('Primera Nacional', 14, 'Quilmes'),
  ('Primera Nacional', 15, 'Racing Cordoba'),
  ('Primera Nacional', 16, 'San Martin Tucuman'),
  ('Primera Nacional', 17, 'San Miguel'),
  ('Primera Nacional', 18, 'Temperley'),
  ('Primera Nacional', 19, 'Tristan Suarez'),
  ('Primera Nacional', 20, 'All Boys'),
  ('MLS', 1, 'Atlanta United'),
  ('MLS', 2, 'Austin FC'),
  ('MLS', 3, 'CF Montreal'),
  ('MLS', 4, 'Charlotte FC'),
  ('MLS', 5, 'Chicago Fire'),
  ('MLS', 6, 'Colorado Rapids'),
  ('MLS', 7, 'Columbus Crew'),
  ('MLS', 8, 'DC United'),
  ('MLS', 9, 'FC Cincinnati'),
  ('MLS', 10, 'FC Dallas'),
  ('MLS', 11, 'Houston Dynamo'),
  ('MLS', 12, 'Inter Miami'),
  ('MLS', 13, 'LA Galaxy'),
  ('MLS', 14, 'Los Angeles FC'),
  ('MLS', 15, 'Minnesota United'),
  ('MLS', 16, 'Nashville SC'),
  ('MLS', 17, 'New England Revolution'),
  ('MLS', 18, 'New York City FC'),
  ('MLS', 19, 'New York Red Bulls'),
  ('MLS', 20, 'Orlando City'),
  ('Liga MX', 1, 'America'),
  ('Liga MX', 2, 'Atlas'),
  ('Liga MX', 3, 'Atletico San Luis'),
  ('Liga MX', 4, 'Cruz Azul'),
  ('Liga MX', 5, 'Guadalajara'),
  ('Liga MX', 6, 'Juarez'),
  ('Liga MX', 7, 'Leon'),
  ('Liga MX', 8, 'Mazatlan'),
  ('Liga MX', 9, 'Monterrey'),
  ('Liga MX', 10, 'Necaxa'),
  ('Liga MX', 11, 'Pachuca'),
  ('Liga MX', 12, 'Puebla'),
  ('Liga MX', 13, 'Pumas UNAM'),
  ('Liga MX', 14, 'Queretaro'),
  ('Liga MX', 15, 'Santos Laguna'),
  ('Liga MX', 16, 'Tigres UANL'),
  ('Liga MX', 17, 'Tijuana'),
  ('Liga MX', 18, 'Toluca'),
  ('Liga MX', 19, 'Club Leon'),
  ('Liga MX', 20, 'Morelia'),
  ('Scottish Premiership', 1, 'Aberdeen'),
  ('Scottish Premiership', 2, 'Celtic'),
  ('Scottish Premiership', 3, 'Dundee'),
  ('Scottish Premiership', 4, 'Dundee United'),
  ('Scottish Premiership', 5, 'Heart of Midlothian'),
  ('Scottish Premiership', 6, 'Hibernian'),
  ('Scottish Premiership', 7, 'Kilmarnock'),
  ('Scottish Premiership', 8, 'Motherwell'),
  ('Scottish Premiership', 9, 'Rangers'),
  ('Scottish Premiership', 10, 'Ross County'),
  ('Scottish Premiership', 11, 'St. Johnstone'),
  ('Scottish Premiership', 12, 'St. Mirren'),
  ('Scottish Championship', 1, 'Airdrieonians'),
  ('Scottish Championship', 2, 'Ayr United'),
  ('Scottish Championship', 3, 'Dunfermline Athletic'),
  ('Scottish Championship', 4, 'Falkirk'),
  ('Scottish Championship', 5, 'Greenock Morton'),
  ('Scottish Championship', 6, 'Hamilton Academical'),
  ('Scottish Championship', 7, 'Livingston'),
  ('Scottish Championship', 8, 'Partick Thistle'),
  ('Scottish Championship', 9, 'Queen''s Park'),
  ('Scottish Championship', 10, 'Raith Rovers'),
  ('Saudi Pro League', 1, 'Abha'),
  ('Saudi Pro League', 2, 'Al Akhdoud'),
  ('Saudi Pro League', 3, 'Al Ettifaq'),
  ('Saudi Pro League', 4, 'Al Fateh'),
  ('Saudi Pro League', 5, 'Al Feiha'),
  ('Saudi Pro League', 6, 'Al Hilal'),
  ('Saudi Pro League', 7, 'Al Ittihad'),
  ('Saudi Pro League', 8, 'Al Khaleej'),
  ('Saudi Pro League', 9, 'Al Nassr'),
  ('Saudi Pro League', 10, 'Al Raed'),
  ('Saudi Pro League', 11, 'Al Riyadh'),
  ('Saudi Pro League', 12, 'Al Shabab'),
  ('Saudi Pro League', 13, 'Al Taawoun'),
  ('Saudi Pro League', 14, 'Al Tai'),
  ('Saudi Pro League', 15, 'Al Wehda'),
  ('Saudi Pro League', 16, 'Al Ahli'),
  ('Saudi Pro League', 17, 'Al Qadsiah'),
  ('Saudi Pro League', 18, 'Damac'),
  ('Saudi Pro League', 19, 'Al Orobah'),
  ('Saudi Pro League', 20, 'Al Kholood'),
  ('J1 League', 1, 'Albirex Niigata'),
  ('J1 League', 2, 'Avispa Fukuoka'),
  ('J1 League', 3, 'Cerezo Osaka'),
  ('J1 League', 4, 'FC Tokyo'),
  ('J1 League', 5, 'Gamba Osaka'),
  ('J1 League', 6, 'Kashima Antlers'),
  ('J1 League', 7, 'Kashiwa Reysol'),
  ('J1 League', 8, 'Kawasaki Frontale'),
  ('J1 League', 9, 'Kyoto Sanga'),
  ('J1 League', 10, 'Machida Zelvia'),
  ('J1 League', 11, 'Nagoya Grampus'),
  ('J1 League', 12, 'Sagan Tosu'),
  ('J1 League', 13, 'Sanfrecce Hiroshima'),
  ('J1 League', 14, 'Shonan Bellmare'),
  ('J1 League', 15, 'Tokyo Verdy'),
  ('J1 League', 16, 'Urawa Red Diamonds'),
  ('J1 League', 17, 'Vissel Kobe'),
  ('J1 League', 18, 'Yokohama F. Marinos'),
  ('J1 League', 19, 'Yokohama FC'),
  ('J1 League', 20, 'Jubilo Iwata'),
  ('J2 League', 1, 'Blaublitz Akita'),
  ('J2 League', 2, 'Ehime FC'),
  ('J2 League', 3, 'Fagiano Okayama'),
  ('J2 League', 4, 'Fujieda MYFC'),
  ('J2 League', 5, 'Iwaki FC'),
  ('J2 League', 6, 'JEF United Chiba'),
  ('J2 League', 7, 'Mito HollyHock'),
  ('J2 League', 8, 'Montedio Yamagata'),
  ('J2 League', 9, 'Oita Trinita'),
  ('J2 League', 10, 'Renofa Yamaguchi'),
  ('J2 League', 11, 'Roasso Kumamoto'),
  ('J2 League', 12, 'Shimizu S-Pulse'),
  ('J2 League', 13, 'Thespakusatsu Gunma'),
  ('J2 League', 14, 'Tokushima Vortis'),
  ('J2 League', 15, 'Tochigi SC'),
  ('J2 League', 16, 'V-Varen Nagasaki'),
  ('J2 League', 17, 'Vegalta Sendai'),
  ('J2 League', 18, 'Ventforet Kofu'),
  ('J2 League', 19, 'Yokohama FC'),
  ('J2 League', 20, 'Kagoshima United'),
  ('K League 1', 1, 'Daegu FC'),
  ('K League 1', 2, 'Daejeon Hana Citizen'),
  ('K League 1', 3, 'FC Seoul'),
  ('K League 1', 4, 'Gangwon FC'),
  ('K League 1', 5, 'Gimcheon Sangmu'),
  ('K League 1', 6, 'Gwangju FC'),
  ('K League 1', 7, 'Incheon United'),
  ('K League 1', 8, 'Jeju United'),
  ('K League 1', 9, 'Jeonbuk Hyundai Motors'),
  ('K League 1', 10, 'Pohang Steelers'),
  ('K League 1', 11, 'Suwon FC'),
  ('K League 1', 12, 'Ulsan HD'),
  ('K League 1', 13, 'Busan IPark'),
  ('K League 1', 14, 'Seongnam FC'),
  ('K League 1', 15, 'Anyang'),
  ('K League 1', 16, 'Bucheon FC'),
  ('K League 1', 17, 'Cheongju FC'),
  ('K League 1', 18, 'Gyeongnam FC'),
  ('K League 1', 19, 'Jeonnam Dragons'),
  ('K League 1', 20, 'Suwon Samsung Bluewings'),
  ('A-League', 1, 'Adelaide United'),
  ('A-League', 2, 'Auckland FC'),
  ('A-League', 3, 'Brisbane Roar'),
  ('A-League', 4, 'Central Coast Mariners'),
  ('A-League', 5, 'Macarthur FC'),
  ('A-League', 6, 'Melbourne City'),
  ('A-League', 7, 'Melbourne Victory'),
  ('A-League', 8, 'Newcastle Jets'),
  ('A-League', 9, 'Perth Glory'),
  ('A-League', 10, 'Sydney FC'),
  ('A-League', 11, 'Wellington Phoenix'),
  ('A-League', 12, 'Western Sydney Wanderers'),
  ('A-League', 13, 'Western United'),
  ('A-League', 14, 'Canberra United'),
  ('A-League', 15, 'Gold Coast United'),
  ('A-League', 16, 'North Queensland Fury'),
  ('A-League', 17, 'South Melbourne'),
  ('A-League', 18, 'Sydney Olympic'),
  ('A-League', 19, 'Wollongong Wolves'),
  ('A-League', 20, 'Adelaide City'),
  ('Danish Superliga', 1, 'Aalborg'),
  ('Danish Superliga', 2, 'AGF'),
  ('Danish Superliga', 3, 'Brondby'),
  ('Danish Superliga', 4, 'FC Copenhagen'),
  ('Danish Superliga', 5, 'FC Midtjylland'),
  ('Danish Superliga', 6, 'Lyngby'),
  ('Danish Superliga', 7, 'Nordsjaelland'),
  ('Danish Superliga', 8, 'Randers'),
  ('Danish Superliga', 9, 'Silkeborg'),
  ('Danish Superliga', 10, 'Sonderjyske'),
  ('Danish Superliga', 11, 'Vejle'),
  ('Danish Superliga', 12, 'Viborg'),
  ('Swiss Super League', 1, 'Basel'),
  ('Swiss Super League', 2, 'Grasshopper'),
  ('Swiss Super League', 3, 'Lausanne-Sport'),
  ('Swiss Super League', 4, 'Lugano'),
  ('Swiss Super League', 5, 'Luzern'),
  ('Swiss Super League', 6, 'Servette'),
  ('Swiss Super League', 7, 'Sion'),
  ('Swiss Super League', 8, 'St. Gallen'),
  ('Swiss Super League', 9, 'Winterthur'),
  ('Swiss Super League', 10, 'Young Boys'),
  ('Swiss Super League', 11, 'Yverdon'),
  ('Swiss Super League', 12, 'Zurich'),
  ('Austrian Bundesliga', 1, 'Austria Klagenfurt'),
  ('Austrian Bundesliga', 2, 'Austria Vienna'),
  ('Austrian Bundesliga', 3, 'BW Linz'),
  ('Austrian Bundesliga', 4, 'Hartberg'),
  ('Austrian Bundesliga', 5, 'LASK'),
  ('Austrian Bundesliga', 6, 'Rapid Vienna'),
  ('Austrian Bundesliga', 7, 'Red Bull Salzburg'),
  ('Austrian Bundesliga', 8, 'Sturm Graz'),
  ('Austrian Bundesliga', 9, 'Tirol'),
  ('Austrian Bundesliga', 10, 'Wolfsberger AC'),
  ('Austrian Bundesliga', 11, 'Altach'),
  ('Austrian Bundesliga', 12, 'Grazer AK'),
  ('Greek Super League', 1, 'AEK Athens'),
  ('Greek Super League', 2, 'Asteras Tripolis'),
  ('Greek Super League', 3, 'Atromitos'),
  ('Greek Super League', 4, 'Lamia'),
  ('Greek Super League', 5, 'OFI Crete'),
  ('Greek Super League', 6, 'Olympiacos'),
  ('Greek Super League', 7, 'Panathinaikos'),
  ('Greek Super League', 8, 'PAOK'),
  ('Greek Super League', 9, 'Aris'),
  ('Greek Super League', 10, 'Volos'),
  ('Greek Super League', 11, 'Panserraikos'),
  ('Greek Super League', 12, 'Kallithea'),
  ('Greek Super League', 13, 'Levadiakos'),
  ('Greek Super League', 14, 'AEL'),
  ('Greek Super League', 15, 'PAS Giannina'),
  ('Greek Super League', 16, 'Panetolikos'),
  ('Greek Super League', 17, 'Ionikos'),
  ('Greek Super League', 18, 'Apollon Smyrnis'),
  ('Greek Super League', 19, 'Ergotelis'),
  ('Greek Super League', 20, 'Xanthi'),
  ('Polish Ekstraklasa', 1, 'Cracovia'),
  ('Polish Ekstraklasa', 2, 'GKS Katowice'),
  ('Polish Ekstraklasa', 3, 'Gornik Zabrze'),
  ('Polish Ekstraklasa', 4, 'Jagiellonia Bialystok'),
  ('Polish Ekstraklasa', 5, 'Korona Kielce'),
  ('Polish Ekstraklasa', 6, 'Lech Poznan'),
  ('Polish Ekstraklasa', 7, 'Legia Warsaw'),
  ('Polish Ekstraklasa', 8, 'Lechia Gdansk'),
  ('Polish Ekstraklasa', 9, 'Motor Lublin'),
  ('Polish Ekstraklasa', 10, 'Piast Gliwice'),
  ('Polish Ekstraklasa', 11, 'Pogon Szczecin'),
  ('Polish Ekstraklasa', 12, 'Puszcza Niepolomice'),
  ('Polish Ekstraklasa', 13, 'Radomiak Radom'),
  ('Polish Ekstraklasa', 14, 'Rakow Czestochowa'),
  ('Polish Ekstraklasa', 15, 'Slask Wroclaw'),
  ('Polish Ekstraklasa', 16, 'Stal Mielec'),
  ('Polish Ekstraklasa', 17, 'Widzew Lodz'),
  ('Polish Ekstraklasa', 18, 'Zaglebie Lubin'),
  ('Polish Ekstraklasa', 19, 'Arka Gdynia'),
  ('Polish Ekstraklasa', 20, 'Wisla Krakow'),
  ('Czech First League', 1, 'Banik Ostrava'),
  ('Czech First League', 2, 'Bohemians 1905'),
  ('Czech First League', 3, 'Ceske Budejovice'),
  ('Czech First League', 4, 'Dukla Prague'),
  ('Czech First League', 5, 'Hradec Kralove'),
  ('Czech First League', 6, 'Jablonec'),
  ('Czech First League', 7, 'Karvina'),
  ('Czech First League', 8, 'Liberec'),
  ('Czech First League', 9, 'Mlada Boleslav'),
  ('Czech First League', 10, 'Olomouc'),
  ('Czech First League', 11, 'Pardubice'),
  ('Czech First League', 12, 'Plzen'),
  ('Czech First League', 13, 'Slavia Prague'),
  ('Czech First League', 14, 'Slovacko'),
  ('Czech First League', 15, 'Sparta Prague'),
  ('Czech First League', 16, 'Teplice'),
  ('Czech First League', 17, 'Vyskov'),
  ('Czech First League', 18, 'Brno'),
  ('Czech First League', 19, 'Opava'),
  ('Czech First League', 20, 'Zlin'),
  ('Ukrainian Premier League', 1, 'Chornomorets Odesa'),
  ('Ukrainian Premier League', 2, 'Dynamo Kyiv'),
  ('Ukrainian Premier League', 3, 'Inhulets'),
  ('Ukrainian Premier League', 4, 'Karpaty Lviv'),
  ('Ukrainian Premier League', 5, 'Kolos Kovalivka'),
  ('Ukrainian Premier League', 6, 'Kryvbas Kryvyi Rih'),
  ('Ukrainian Premier League', 7, 'LNZ Cherkasy'),
  ('Ukrainian Premier League', 8, 'Obolon Kyiv'),
  ('Ukrainian Premier League', 9, 'Oleksandriya'),
  ('Ukrainian Premier League', 10, 'Polissya Zhytomyr'),
  ('Ukrainian Premier League', 11, 'Rukh Lviv'),
  ('Ukrainian Premier League', 12, 'Shakhtar Donetsk'),
  ('Ukrainian Premier League', 13, 'Veres Rivne'),
  ('Ukrainian Premier League', 14, 'Vorskla Poltava'),
  ('Ukrainian Premier League', 15, 'Zorya Luhansk'),
  ('Ukrainian Premier League', 16, 'Metalist 1925'),
  ('Ukrainian Premier League', 17, 'Dnipro-1'),
  ('Ukrainian Premier League', 18, 'Hoverla Uzhhorod'),
  ('Ukrainian Premier League', 19, 'Illichivets'),
  ('Ukrainian Premier League', 20, 'Sevastopol'),
  ('Romanian SuperLiga', 1, 'CFR Cluj'),
  ('Romanian SuperLiga', 2, 'Dinamo Bucuresti'),
  ('Romanian SuperLiga', 3, 'Farul Constanta'),
  ('Romanian SuperLiga', 4, 'FCSB'),
  ('Romanian SuperLiga', 5, 'Hermannstadt'),
  ('Romanian SuperLiga', 6, 'Otelul Galati'),
  ('Romanian SuperLiga', 7, 'Petrolul Ploiesti'),
  ('Romanian SuperLiga', 8, 'Rapid Bucuresti'),
  ('Romanian SuperLiga', 9, 'Sepsi OSK'),
  ('Romanian SuperLiga', 10, 'Universitatea Cluj'),
  ('Romanian SuperLiga', 11, 'Universitatea Craiova'),
  ('Romanian SuperLiga', 12, 'UTA Arad'),
  ('Romanian SuperLiga', 13, 'Unirea Slobozia'),
  ('Romanian SuperLiga', 14, 'Botosani'),
  ('Romanian SuperLiga', 15, 'Politehnica Iasi'),
  ('Romanian SuperLiga', 16, 'Gloria Buzau'),
  ('Romanian SuperLiga', 17, 'Steaua Bucuresti'),
  ('Romanian SuperLiga', 18, 'Voluntari'),
  ('Romanian SuperLiga', 19, 'Astra Giurgiu'),
  ('Romanian SuperLiga', 20, 'Viitorul'),
  ('Serbian SuperLiga', 1, 'Backa Topola'),
  ('Serbian SuperLiga', 2, 'Cukaricki'),
  ('Serbian SuperLiga', 3, 'Crvena zvezda'),
  ('Serbian SuperLiga', 4, 'IMT Belgrade'),
  ('Serbian SuperLiga', 5, 'Jedinstvo Ub'),
  ('Serbian SuperLiga', 6, 'Mladost Lucani'),
  ('Serbian SuperLiga', 7, 'Napredak'),
  ('Serbian SuperLiga', 8, 'Novi Pazar'),
  ('Serbian SuperLiga', 9, 'OFK Belgrade'),
  ('Serbian SuperLiga', 10, 'Partizan'),
  ('Serbian SuperLiga', 11, 'Radnicki 1923'),
  ('Serbian SuperLiga', 12, 'Radnicki Nis'),
  ('Serbian SuperLiga', 13, 'Spartak Subotica'),
  ('Serbian SuperLiga', 14, 'Tekstilac Odzaci'),
  ('Serbian SuperLiga', 15, 'Vojvodina'),
  ('Serbian SuperLiga', 16, 'Zeleznicar Pancevo'),
  ('Serbian SuperLiga', 17, 'Javor Ivanjica'),
  ('Serbian SuperLiga', 18, 'Indjija'),
  ('Serbian SuperLiga', 19, 'Metalac Gornji Milanovac'),
  ('Serbian SuperLiga', 20, 'Kolubara'),
  ('Croatian League', 1, 'Dinamo Zagreb'),
  ('Croatian League', 2, 'Hajduk Split'),
  ('Croatian League', 3, 'Istra 1961'),
  ('Croatian League', 4, 'Lokomotiva Zagreb'),
  ('Croatian League', 5, 'Osijek'),
  ('Croatian League', 6, 'Rijeka'),
  ('Croatian League', 7, 'Sibenik'),
  ('Croatian League', 8, 'Slaven Belupo'),
  ('Croatian League', 9, 'Varazdin'),
  ('Croatian League', 10, 'Gorica'),
  ('Norwegian Eliteserien', 1, 'Bodo/Glimt'),
  ('Norwegian Eliteserien', 2, 'Brann'),
  ('Norwegian Eliteserien', 3, 'Fredrikstad'),
  ('Norwegian Eliteserien', 4, 'HamKam'),
  ('Norwegian Eliteserien', 5, 'Haugesund'),
  ('Norwegian Eliteserien', 6, 'KFUM Oslo'),
  ('Norwegian Eliteserien', 7, 'Kristiansund'),
  ('Norwegian Eliteserien', 8, 'Lillestrom'),
  ('Norwegian Eliteserien', 9, 'Molde'),
  ('Norwegian Eliteserien', 10, 'Odd'),
  ('Norwegian Eliteserien', 11, 'Rosenborg'),
  ('Norwegian Eliteserien', 12, 'Sandefjord'),
  ('Norwegian Eliteserien', 13, 'Sarpsborg 08'),
  ('Norwegian Eliteserien', 14, 'Stromsgodset'),
  ('Norwegian Eliteserien', 15, 'Tromso'),
  ('Norwegian Eliteserien', 16, 'Viking'),
  ('Norwegian Eliteserien', 17, 'Valerenga'),
  ('Norwegian Eliteserien', 18, 'Aalesund'),
  ('Norwegian Eliteserien', 19, 'Start'),
  ('Norwegian Eliteserien', 20, 'Sogndal'),
  ('Swedish Allsvenskan', 1, 'AIK'),
  ('Swedish Allsvenskan', 2, 'Brommapojkarna'),
  ('Swedish Allsvenskan', 3, 'Degerfors'),
  ('Swedish Allsvenskan', 4, 'Djurgarden'),
  ('Swedish Allsvenskan', 5, 'Elfsborg'),
  ('Swedish Allsvenskan', 6, 'GAIS'),
  ('Swedish Allsvenskan', 7, 'Goteborg'),
  ('Swedish Allsvenskan', 8, 'Hacken'),
  ('Swedish Allsvenskan', 9, 'Halmstad'),
  ('Swedish Allsvenskan', 10, 'Hammarby'),
  ('Swedish Allsvenskan', 11, 'IFK Norrkoping'),
  ('Swedish Allsvenskan', 12, 'Kalmar'),
  ('Swedish Allsvenskan', 13, 'Malmo'),
  ('Swedish Allsvenskan', 14, 'Mjallby'),
  ('Swedish Allsvenskan', 15, 'Sirius'),
  ('Swedish Allsvenskan', 16, 'Varnamo'),
  ('Swedish Allsvenskan', 17, 'Orebro'),
  ('Swedish Allsvenskan', 18, 'Helsingborg'),
  ('Swedish Allsvenskan', 19, 'Trelleborg'),
  ('Swedish Allsvenskan', 20, 'Sundsvall'),
  ('Finnish Veikkausliiga', 1, 'AC Oulu'),
  ('Finnish Veikkausliiga', 2, 'EIF'),
  ('Finnish Veikkausliiga', 3, 'Gnistan'),
  ('Finnish Veikkausliiga', 4, 'Haka'),
  ('Finnish Veikkausliiga', 5, 'HJK'),
  ('Finnish Veikkausliiga', 6, 'Ilves'),
  ('Finnish Veikkausliiga', 7, 'Inter Turku'),
  ('Finnish Veikkausliiga', 8, 'KuPS'),
  ('Finnish Veikkausliiga', 9, 'Lahti'),
  ('Finnish Veikkausliiga', 10, 'SJK'),
  ('Finnish Veikkausliiga', 11, 'VPS'),
  ('Finnish Veikkausliiga', 12, 'Mariehamn'),
  ('Chinese Super League', 1, 'Beijing Guoan'),
  ('Chinese Super League', 2, 'Cangzhou Mighty Lions'),
  ('Chinese Super League', 3, 'Changchun Yatai'),
  ('Chinese Super League', 4, 'Chengdu Rongcheng'),
  ('Chinese Super League', 5, 'Henan'),
  ('Chinese Super League', 6, 'Meizhou Hakka'),
  ('Chinese Super League', 7, 'Nantong Zhiyun'),
  ('Chinese Super League', 8, 'Qingdao Hainiu'),
  ('Chinese Super League', 9, 'Qingdao West Coast'),
  ('Chinese Super League', 10, 'Shanghai Port'),
  ('Chinese Super League', 11, 'Shanghai Shenhua'),
  ('Chinese Super League', 12, 'Shandong Taishan'),
  ('Chinese Super League', 13, 'Shenzhen Peng City'),
  ('Chinese Super League', 14, 'Tianjin Jinmen Tiger'),
  ('Chinese Super League', 15, 'Wuhan Three Towns'),
  ('Chinese Super League', 16, 'Zhejiang'),
  ('Chinese Super League', 17, 'Guangzhou'),
  ('Chinese Super League', 18, 'Dalian Pro'),
  ('Chinese Super League', 19, 'Hebei'),
  ('Chinese Super League', 20, 'Jiangsu'),
  ('Indian Super League', 1, 'Bengaluru FC'),
  ('Indian Super League', 2, 'Chennaiyin FC'),
  ('Indian Super League', 3, 'East Bengal'),
  ('Indian Super League', 4, 'FC Goa'),
  ('Indian Super League', 5, 'Hyderabad FC'),
  ('Indian Super League', 6, 'Jamshedpur FC'),
  ('Indian Super League', 7, 'Kerala Blasters'),
  ('Indian Super League', 8, 'Mohun Bagan'),
  ('Indian Super League', 9, 'Mumbai City'),
  ('Indian Super League', 10, 'NorthEast United'),
  ('Indian Super League', 11, 'Odisha FC'),
  ('Indian Super League', 12, 'Punjab FC'),
  ('South African Premiership', 1, 'AmaZulu'),
  ('South African Premiership', 2, 'Cape Town City'),
  ('South African Premiership', 3, 'Chippa United'),
  ('South African Premiership', 4, 'Golden Arrows'),
  ('South African Premiership', 5, 'Kaizer Chiefs'),
  ('South African Premiership', 6, 'Magesi FC'),
  ('South African Premiership', 7, 'Mamelodi Sundowns'),
  ('South African Premiership', 8, 'Marumo Gallants'),
  ('South African Premiership', 9, 'Orlando Pirates'),
  ('South African Premiership', 10, 'Polokwane City'),
  ('South African Premiership', 11, 'Richards Bay'),
  ('South African Premiership', 12, 'Sekhukhune United'),
  ('South African Premiership', 13, 'Stellenbosch'),
  ('South African Premiership', 14, 'SuperSport United'),
  ('South African Premiership', 15, 'TS Galaxy'),
  ('South African Premiership', 16, 'Royal AM'),
  ('South African Premiership', 17, 'Ajax Cape Town'),
  ('South African Premiership', 18, 'Bloemfontein Celtic'),
  ('South African Premiership', 19, 'Bidvest Wits'),
  ('South African Premiership', 20, 'Platinum Stars'),
  ('Egyptian Premier League', 1, 'Al Ahly'),
  ('Egyptian Premier League', 2, 'Al Ittihad Alexandria'),
  ('Egyptian Premier League', 3, 'Al Masry'),
  ('Egyptian Premier League', 4, 'Al Mokawloon'),
  ('Egyptian Premier League', 5, 'Bank El Ahly'),
  ('Egyptian Premier League', 6, 'Ceramica Cleopatra'),
  ('Egyptian Premier League', 7, 'El Dakhleya'),
  ('Egyptian Premier League', 8, 'El Gouna'),
  ('Egyptian Premier League', 9, 'ENPPI'),
  ('Egyptian Premier League', 10, 'Future FC'),
  ('Egyptian Premier League', 11, 'Haras El Hodoud'),
  ('Egyptian Premier League', 12, 'Ismaily'),
  ('Egyptian Premier League', 13, 'National Bank'),
  ('Egyptian Premier League', 14, 'Pyramids FC'),
  ('Egyptian Premier League', 15, 'Smouha'),
  ('Egyptian Premier League', 16, 'Talaea El Gaish'),
  ('Egyptian Premier League', 17, 'Zamalek'),
  ('Egyptian Premier League', 18, 'ZED FC'),
  ('Egyptian Premier League', 19, 'Pharco'),
  ('Egyptian Premier League', 20, 'Modern Sport'),
  ('Moroccan Botola', 1, 'FUS Rabat'),
  ('Moroccan Botola', 2, 'Hassania Agadir'),
  ('Moroccan Botola', 3, 'Ittihad Tanger'),
  ('Moroccan Botola', 4, 'JS Soualem'),
  ('Moroccan Botola', 5, 'Moghreb Tetouan'),
  ('Moroccan Botola', 6, 'Olympic Safi'),
  ('Moroccan Botola', 7, 'Raja Casablanca'),
  ('Moroccan Botola', 8, 'Renaissance Berkane'),
  ('Moroccan Botola', 9, 'Renaissance Zemamra'),
  ('Moroccan Botola', 10, 'Wydad Casablanca'),
  ('Moroccan Botola', 11, 'AS FAR'),
  ('Moroccan Botola', 12, 'Difaa El Jadida'),
  ('Moroccan Botola', 13, 'Kawkab Marrakech'),
  ('Moroccan Botola', 14, 'Mouloudia Oujda'),
  ('Moroccan Botola', 15, 'Racing Casablanca'),
  ('Moroccan Botola', 16, 'Youssoufia Berrechid'),
  ('Moroccan Botola', 17, 'KAC Kenitra'),
  ('Moroccan Botola', 18, 'Maghreb Fez'),
  ('Moroccan Botola', 19, 'Chabab Mohammedia'),
  ('Moroccan Botola', 20, 'SCCM Mohammedia'),
  ('Colombian Primera A', 1, 'Aguilas Doradas'),
  ('Colombian Primera A', 2, 'Alianza FC'),
  ('Colombian Primera A', 3, 'America de Cali'),
  ('Colombian Primera A', 4, 'Atletico Bucaramanga'),
  ('Colombian Primera A', 5, 'Atletico Nacional'),
  ('Colombian Primera A', 6, 'Boyaca Chico'),
  ('Colombian Primera A', 7, 'Deportes Tolima'),
  ('Colombian Primera A', 8, 'Deportivo Cali'),
  ('Colombian Primera A', 9, 'Deportivo Pasto'),
  ('Colombian Primera A', 10, 'Envigado'),
  ('Colombian Primera A', 11, 'Fortaleza CEIF'),
  ('Colombian Primera A', 12, 'Independiente Medellin'),
  ('Colombian Primera A', 13, 'Independiente Santa Fe'),
  ('Colombian Primera A', 14, 'Jaguares de Cordoba'),
  ('Colombian Primera A', 15, 'Junior'),
  ('Colombian Primera A', 16, 'La Equidad'),
  ('Colombian Primera A', 17, 'Millonarios'),
  ('Colombian Primera A', 18, 'Once Caldas'),
  ('Colombian Primera A', 19, 'Patriotas'),
  ('Colombian Primera A', 20, 'Pereira'),
  ('Chilean Primera Division', 1, 'Audax Italiano'),
  ('Chilean Primera Division', 2, 'Cobresal'),
  ('Chilean Primera Division', 3, 'Colo-Colo'),
  ('Chilean Primera Division', 4, 'Coquimbo Unido'),
  ('Chilean Primera Division', 5, 'Cobreloa'),
  ('Chilean Primera Division', 6, 'Deportes Iquique'),
  ('Chilean Primera Division', 7, 'Everton de Vina del Mar'),
  ('Chilean Primera Division', 8, 'Huachipato'),
  ('Chilean Primera Division', 9, 'Nublense'),
  ('Chilean Primera Division', 10, 'O''Higgins'),
  ('Chilean Primera Division', 11, 'Palestino'),
  ('Chilean Primera Division', 12, 'Universidad Catolica'),
  ('Chilean Primera Division', 13, 'Universidad de Chile'),
  ('Chilean Primera Division', 14, 'Union Espanola'),
  ('Chilean Primera Division', 15, 'Union La Calera'),
  ('Chilean Primera Division', 16, 'Deportes Copiapo'),
  ('Chilean Primera Division', 17, 'Santiago Wanderers'),
  ('Chilean Primera Division', 18, 'Magallanes'),
  ('Chilean Primera Division', 19, 'Curico Unido'),
  ('Chilean Primera Division', 20, 'Antofagasta'),
  ('Peruvian Liga 1', 1, 'ADT'),
  ('Peruvian Liga 1', 2, 'Alianza Atletico'),
  ('Peruvian Liga 1', 3, 'Alianza Lima'),
  ('Peruvian Liga 1', 4, 'Atletico Grau'),
  ('Peruvian Liga 1', 5, 'Carlos A. Mannucci'),
  ('Peruvian Liga 1', 6, 'Cienciano'),
  ('Peruvian Liga 1', 7, 'Comerciantes Unidos'),
  ('Peruvian Liga 1', 8, 'Cusco FC'),
  ('Peruvian Liga 1', 9, 'Deportivo Garcilaso'),
  ('Peruvian Liga 1', 10, 'FBC Melgar'),
  ('Peruvian Liga 1', 11, 'Los Chankas'),
  ('Peruvian Liga 1', 12, 'Sport Boys'),
  ('Peruvian Liga 1', 13, 'Sport Huancayo'),
  ('Peruvian Liga 1', 14, 'Sporting Cristal'),
  ('Peruvian Liga 1', 15, 'Universitario'),
  ('Peruvian Liga 1', 16, 'Union Comercio'),
  ('Peruvian Liga 1', 17, 'UTC'),
  ('Peruvian Liga 1', 18, 'Cesar Vallejo'),
  ('Peruvian Liga 1', 19, 'Binacional'),
  ('Peruvian Liga 1', 20, 'Ayacucho FC')
;

with target_leagues as (
  select l.id, l.name, l.country, l.reputation, l.tier
  from leagues l
  join _league_seed ls on ls.name = l.name and ls.country = l.country
),
target_clubs as (
  select
    tl.id as league_id,
    cs.club_order,
    cs.club_name,
    tl.reputation,
    tl.tier
  from target_leagues tl
  join _club_seed cs on cs.league_name = tl.name
)
insert into clubs (league_id, name, reputation, finances, transfer_budget, wage_budget)
select
  tc.league_id,
  tc.club_name,
  greatest(
    1,
    least(
      100,
      case
        when tc.tier = 1 and tc.club_order <= 2 then 90 + ((abs(hashtext(tc.club_name)) + tc.club_order) % 11)
        when tc.club_order <= 8 then 80 + ((abs(hashtext(tc.club_name)) + tc.club_order) % 10)
        when tc.club_order <= 13 then 70 + ((abs(hashtext(tc.club_name)) + tc.club_order) % 10)
        when tc.club_order <= 17 then 60 + ((abs(hashtext(tc.club_name)) + tc.club_order) % 10)
        else 50 + ((abs(hashtext(tc.club_name)) + tc.club_order) % 10)
      end
    )
  ),
  case
    when tc.club_order <= 8 then 150000000 + (abs(hashtext(tc.club_name || ':fin')) % 350000001)
    when tc.club_order <= 13 then 40000000 + (abs(hashtext(tc.club_name || ':fin')) % 110000001)
    when tc.club_order <= 17 then 10000000 + (abs(hashtext(tc.club_name || ':fin')) % 50000001)
    else 1000000 + (abs(hashtext(tc.club_name || ':fin')) % 14000001)
  end,
  case
    when tc.club_order <= 8 then round((150000000 + (abs(hashtext(tc.club_name || ':fin')) % 350000001)) * 0.30)
    when tc.club_order <= 13 then round((40000000 + (abs(hashtext(tc.club_name || ':fin')) % 110000001)) * 0.28)
    when tc.club_order <= 17 then round((10000000 + (abs(hashtext(tc.club_name || ':fin')) % 50000001)) * 0.26)
    else round((1000000 + (abs(hashtext(tc.club_name || ':fin')) % 14000001)) * 0.24)
  end,
  case
    when tc.club_order <= 8 then round((150000000 + (abs(hashtext(tc.club_name || ':fin')) % 350000001)) * 0.40)
    when tc.club_order <= 13 then round((40000000 + (abs(hashtext(tc.club_name || ':fin')) % 110000001)) * 0.38)
    when tc.club_order <= 17 then round((10000000 + (abs(hashtext(tc.club_name || ':fin')) % 50000001)) * 0.35)
    else round((1000000 + (abs(hashtext(tc.club_name || ':fin')) % 14000001)) * 0.33)
  end
from target_clubs tc
where not exists (
  select 1
  from clubs c
  where c.league_id = tc.league_id and c.name = tc.club_name
);

with target_clubs as (
  select c.id, c.name, l.country
  from clubs c
  join leagues l on l.id = c.league_id
  join _league_seed ls on ls.name = l.name and ls.country = l.country
)
insert into players (
  club_id, name, age, nationality, preferred_position, potential,
  pace, shooting, passing, dribbling, defending, physical
)
select
  tc.id,
  format('%s Player %s', tc.name, player_index.i),
  18 + ((player_index.i * 3 + length(tc.name)) % 17),
  tc.country,
  case
    when player_index.i <= 2 then 'GK'
    when player_index.i <= 8 then 'DEF'
    when player_index.i <= 16 then 'MID'
    else 'ATT'
  end,
  58 + ((player_index.i * 2 + length(tc.name)) % 35),
  50 + ((player_index.i * 3 + length(tc.name)) % 45),
  50 + ((player_index.i * 5 + length(tc.name)) % 45),
  50 + ((player_index.i * 7 + length(tc.name)) % 45),
  50 + ((player_index.i * 11 + length(tc.name)) % 45),
  50 + ((player_index.i * 13 + length(tc.name)) % 45),
  50 + ((player_index.i * 17 + length(tc.name)) % 45)
from target_clubs tc
cross join generate_series(1, 25) as player_index(i)
where not exists (
  select 1
  from players p
  where p.club_id = tc.id and p.name = format('%s Player %s', tc.name, player_index.i)
);

insert into national_team_jobs (nation, reputation_required)
select
  format('National Team %s', s.i),
  case when s.i <= 10 then 88 when s.i <= 40 then 70 else 52 end
from generate_series(1, 110) as s(i)
on conflict (nation) do nothing;

insert into seasons (current_matchday, status, completed)
select 1, 'active', false
where not exists (
  select 1 from seasons
);
