export type LeagueSeed = {
  name: string;
  country: string;
  reputation: number;
};

export type PlayerSeed = {
  name: string;
  age: number;
  nationality: string;
  preferredPosition: string;
};

export type ClubSeed = {
  name: string;
  leagueName: string;
  country: string;
  reputation: number;
  financeBalance: number;
  managerQuality: number;
  tacticalStyle: "balanced" | "pressing" | "counter" | "possession";
  players: PlayerSeed[];
};

const leagueNames = [
  ["Premier League", "England"],
  ["Championship", "England"],
  ["League One", "England"],
  ["La Liga", "Spain"],
  ["La Liga 2", "Spain"],
  ["Primera RFEF", "Spain"],
  ["Serie A", "Italy"],
  ["Serie B", "Italy"],
  ["Bundesliga", "Germany"],
  ["2. Bundesliga", "Germany"],
  ["Ligue 1", "France"],
  ["Ligue 2", "France"],
  ["Eredivisie", "Netherlands"],
  ["Primeira Liga", "Portugal"],
  ["Belgian Pro League", "Belgium"],
  ["Super Lig", "Turkey"],
  ["Brasileirao", "Brazil"],
  ["Serie B Brasil", "Brazil"],
  ["Liga Profesional", "Argentina"],
  ["Primera Nacional", "Argentina"],
  ["MLS", "United States"],
  ["Liga MX", "Mexico"],
  ["Scottish Premiership", "Scotland"],
  ["Scottish Championship", "Scotland"],
  ["Saudi Pro League", "Saudi Arabia"],
  ["J1 League", "Japan"],
  ["J2 League", "Japan"],
  ["K League 1", "South Korea"],
  ["A-League", "Australia"],
  ["Danish Superliga", "Denmark"],
  ["Swiss Super League", "Switzerland"],
  ["Austrian Bundesliga", "Austria"],
  ["Greek Super League", "Greece"],
  ["Polish Ekstraklasa", "Poland"],
  ["Czech First League", "Czech Republic"],
  ["Ukrainian Premier League", "Ukraine"],
  ["Romanian SuperLiga", "Romania"],
  ["Serbian SuperLiga", "Serbia"],
  ["Croatian League", "Croatia"],
  ["Norwegian Eliteserien", "Norway"],
  ["Swedish Allsvenskan", "Sweden"],
  ["Finnish Veikkausliiga", "Finland"],
  ["Chinese Super League", "China"],
  ["Indian Super League", "India"],
  ["South African Premiership", "South Africa"],
  ["Egyptian Premier League", "Egypt"],
  ["Moroccan Botola", "Morocco"],
  ["Colombian Primera A", "Colombia"],
  ["Chilean Primera Division", "Chile"],
  ["Peruvian Liga 1", "Peru"],
] as const;

const nationalTeams = [
  "Argentina", "Australia", "Austria", "Belgium", "Bolivia", "Bosnia and Herzegovina",
  "Brazil", "Bulgaria", "Cameroon", "Canada", "Chile", "China", "Colombia", "Costa Rica",
  "Croatia", "Czech Republic", "Denmark", "Ecuador", "Egypt", "England", "Finland", "France",
  "Germany", "Ghana", "Greece", "Hungary", "Iceland", "India", "Iran", "Iraq", "Ireland",
  "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kenya", "Mexico", "Morocco",
  "Netherlands", "New Zealand", "Nigeria", "North Macedonia", "Norway", "Paraguay", "Peru",
  "Poland", "Portugal", "Qatar", "Romania", "Saudi Arabia", "Scotland", "Senegal", "Serbia",
  "Slovakia", "Slovenia", "South Africa", "South Korea", "Spain", "Sweden", "Switzerland", "Tunisia",
  "Turkey", "Ukraine", "United States", "Uruguay", "Venezuela", "Wales", "Algeria", "Albania",
  "Angola", "Armenia", "Azerbaijan", "Belarus", "Benin", "Congo", "Cyprus", "DR Congo", "El Salvador",
  "Estonia", "Georgia", "Guatemala", "Honduras", "Kazakhstan", "Kosovo", "Latvia", "Lithuania",
  "Luxembourg", "Mali", "Montenegro", "Mozambique", "Northern Ireland", "Oman", "Panama", "Syria",
  "Tanzania", "Trinidad and Tobago", "Uganda", "United Arab Emirates", "Uzbekistan", "Vietnam",
  "Zambia", "Zimbabwe", "Guinea", "Burkina Faso", "Gabon", "Libya", "Madagascar", "Mauritania",
] as const;

export const topLeagues: LeagueSeed[] = leagueNames.map(([name, country], index) => ({
  name,
  country,
  reputation: Math.max(45, 95 - index),
}));

export const topNationalTeams = nationalTeams.slice(0, 110);

const defaultClubCount = 20;

const clubCountByLeague: Record<string, number> = {
  Championship: 24,
  "League One": 24,
  "La Liga 2": 22,
  "2. Bundesliga": 18,
  "Ligue 1": 18,
  "Ligue 2": 18,
  Eredivisie: 18,
  "Primeira Liga": 18,
  "Belgian Pro League": 16,
  "Scottish Premiership": 12,
  "Scottish Championship": 10,
  "Swiss Super League": 12,
  "Austrian Bundesliga": 12,
  "Danish Superliga": 12,
  "Croatian League": 10,
  "Finnish Veikkausliiga": 12,
  "Indian Super League": 12,
};

export const getLeagueKey = (league: Pick<LeagueSeed, "name" | "country">) =>
  `${league.name} • ${league.country}`;

const realClubNamesByLeague: Record<string, string[]> = {
  "Premier League": [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton & Hove Albion",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Ipswich Town",
    "Leicester City",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Southampton",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton Wanderers",
  ],
  Championship: [
    "Blackburn Rovers",
    "Bristol City",
    "Burnley",
    "Cardiff City",
    "Coventry City",
    "Derby County",
    "Hull City",
    "Leeds United",
    "Luton Town",
    "Middlesbrough",
    "Millwall",
    "Norwich City",
    "Oxford United",
    "Plymouth Argyle",
    "Portsmouth",
    "Preston North End",
    "Queens Park Rangers",
    "Sheffield United",
    "Sheffield Wednesday",
    "Stoke City",
    "Sunderland",
    "Swansea City",
    "Watford",
    "West Bromwich Albion",
  ],
  "League One": [
    "Barnsley",
    "Blackpool",
    "Bolton Wanderers",
    "Bristol Rovers",
    "Burton Albion",
    "Cambridge United",
    "Charlton Athletic",
    "Exeter City",
    "Huddersfield Town",
    "Leyton Orient",
    "Lincoln City",
    "Mansfield Town",
    "Northampton Town",
    "Peterborough United",
    "Reading",
    "Rotherham United",
    "Shrewsbury Town",
    "Stevenage",
    "Stockport County",
    "Wigan Athletic",
    "Wrexham",
    "Wycombe Wanderers",
    "Birmingham City",
    "Crawley Town",
  ],
  "La Liga": [
    "Alaves",
    "Athletic Club",
    "Atletico Madrid",
    "Barcelona",
    "Celta Vigo",
    "Espanyol",
    "Getafe",
    "Girona",
    "Las Palmas",
    "Leganes",
    "Mallorca",
    "Osasuna",
    "Rayo Vallecano",
    "Real Betis",
    "Real Madrid",
    "Real Sociedad",
    "Sevilla",
    "Valencia",
    "Valladolid",
    "Villarreal",
  ],
  "La Liga 2": [
    "Albacete",
    "Almeria",
    "Burgos",
    "Cadiz",
    "Cartagena",
    "Castellon",
    "Cordoba",
    "Deportivo La Coruna",
    "Eibar",
    "Elche",
    "Eldense",
    "Granada",
    "Huesca",
    "Levante",
    "Malaga",
    "Mirandes",
    "Oviedo",
    "Racing Santander",
    "Sporting Gijon",
    "Tenerife",
    "Real Zaragoza",
    "Alcorcon",
  ],
  "Primera RFEF": [
    "Algeciras",
    "Antequera",
    "Arenteiro",
    "Celta Fortuna",
    "Cultural Leonesa",
    "Gimnastic Tarragona",
    "Ibiza",
    "Lugo",
    "Ponferradina",
    "Real Union",
    "Sabadell",
    "Sestao River",
    "Tarazona",
    "Unionistas",
    "Barcelona Atletic",
    "Athletic Bilbao B",
    "Real Madrid Castilla",
    "Murcia",
    "Cordoba B",
    "Merida",
  ],
  "Serie A": [
    "Atalanta",
    "Bologna",
    "Cagliari",
    "Como",
    "Empoli",
    "Fiorentina",
    "Genoa",
    "Hellas Verona",
    "Inter Milan",
    "Juventus",
    "Lazio",
    "Lecce",
    "Milan",
    "Monza",
    "Napoli",
    "Parma",
    "Roma",
    "Torino",
    "Udinese",
    "Venezia",
  ],
  "Serie B": [
    "Bari",
    "Brescia",
    "Carrarese",
    "Catanzaro",
    "Cesena",
    "Cittadella",
    "Cosenza",
    "Cremonese",
    "Frosinone",
    "Juve Stabia",
    "Mantova",
    "Modena",
    "Palermo",
    "Pisa",
    "Reggiana",
    "Salernitana",
    "Sampdoria",
    "Sassuolo",
    "Spezia",
    "Sudtirol",
  ],
  Bundesliga: [
    "Augsburg",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Bochum",
    "Borussia Dortmund",
    "Borussia Monchengladbach",
    "Eintracht Frankfurt",
    "Freiburg",
    "Heidenheim",
    "Holstein Kiel",
    "Hoffenheim",
    "Mainz 05",
    "RB Leipzig",
    "St. Pauli",
    "Stuttgart",
    "Union Berlin",
    "Werder Bremen",
    "Wolfsburg",
  ],
  "2. Bundesliga": [
    "Darmstadt 98",
    "Eintracht Braunschweig",
    "Fortuna Dusseldorf",
    "Greuther Furth",
    "Hamburger SV",
    "Hannover 96",
    "Hertha BSC",
    "Jahn Regensburg",
    "Karlsruher SC",
    "Koln",
    "Magdeburg",
    "Nurnberg",
    "Paderborn",
    "Schalke 04",
    "Ulm",
    "Elversberg",
    "Kaiserslautern",
    "Preussen Munster",
  ],
  "Ligue 1": [
    "Angers",
    "Auxerre",
    "Brest",
    "Le Havre",
    "Lens",
    "Lille",
    "Lyon",
    "Marseille",
    "Monaco",
    "Montpellier",
    "Nantes",
    "Nice",
    "Paris Saint-Germain",
    "Reims",
    "Rennes",
    "Saint-Etienne",
    "Strasbourg",
    "Toulouse",
  ],
  "Ligue 2": [
    "Ajaccio",
    "Amiens",
    "Annecy",
    "Bastia",
    "Caen",
    "Clermont",
    "Dunkerque",
    "Grenoble",
    "Guingamp",
    "Laval",
    "Lorient",
    "Metz",
    "Pau",
    "Red Star",
    "Rodez",
    "Troyes",
    "Paris FC",
    "Martigues",
  ],
  Eredivisie: [
    "Ajax",
    "Almere City",
    "AZ Alkmaar",
    "Feyenoord",
    "Fortuna Sittard",
    "Go Ahead Eagles",
    "Groningen",
    "Heerenveen",
    "Heracles Almelo",
    "NAC Breda",
    "NEC Nijmegen",
    "PEC Zwolle",
    "PSV",
    "RKC Waalwijk",
    "Sparta Rotterdam",
    "Twente",
    "Utrecht",
    "Willem II",
  ],
  "Primeira Liga": [
    "Arouca",
    "AVS",
    "Benfica",
    "Boavista",
    "Braga",
    "Casa Pia",
    "Estoril",
    "Estrela Amadora",
    "Famalicao",
    "Farense",
    "Gil Vicente",
    "Moreirense",
    "Nacional",
    "Porto",
    "Rio Ave",
    "Santa Clara",
    "Sporting CP",
    "Vitoria Guimaraes",
  ],
  "Belgian Pro League": [
    "Anderlecht",
    "Antwerp",
    "Beerschot",
    "Cercle Brugge",
    "Charleroi",
    "Club Brugge",
    "Dender",
    "Genk",
    "Gent",
    "Kortrijk",
    "Leuven",
    "Mechelen",
    "Sint-Truiden",
    "Standard Liege",
    "Union Saint-Gilloise",
    "Westerlo",
  ],
  "Super Lig": [
    "Adana Demirspor",
    "Alanyaspor",
    "Antalyaspor",
    "Besiktas",
    "Bodrum FK",
    "Caykur Rizespor",
    "Eyupspor",
    "Fenerbahce",
    "Galatasaray",
    "Gaziantep",
    "Goztepe",
    "Hatayspor",
    "Kasimpasa",
    "Kayserispor",
    "Konyaspor",
    "Samsunspor",
    "Sivasspor",
    "Trabzonspor",
    "Basaksehir",
    "Ankaragucu",
  ],
  Brasileirao: [
    "Atletico Goianiense",
    "Atletico Mineiro",
    "Bahia",
    "Botafogo",
    "Bragantino",
    "Corinthians",
    "Criciuma",
    "Cruzeiro",
    "Cuiaba",
    "Flamengo",
    "Fluminense",
    "Fortaleza",
    "Gremio",
    "Internacional",
    "Juventude",
    "Palmeiras",
    "Sao Paulo",
    "Vasco da Gama",
    "Vitoria",
    "Athletico Paranaense",
  ],
  "Serie B Brasil": [
    "Amazonas",
    "America Mineiro",
    "Avai",
    "Botafogo SP",
    "Brusque",
    "CRB",
    "Ceara",
    "Chapecoense",
    "Coritiba",
    "Goias",
    "Guarani",
    "Ituano",
    "Mirassol",
    "Novorizontino",
    "Operario",
    "Paysandu",
    "Ponte Preta",
    "Santos",
    "Sport Recife",
    "Vila Nova",
  ],
  "Liga Profesional": [
    "Argentinos Juniors",
    "Banfield",
    "Barracas Central",
    "Belgrano",
    "Boca Juniors",
    "Central Cordoba",
    "Defensa y Justicia",
    "Estudiantes",
    "Gimnasia La Plata",
    "Godoy Cruz",
    "Huracan",
    "Independiente",
    "Instituto",
    "Lanus",
    "Newell's Old Boys",
    "Racing Club",
    "River Plate",
    "Rosario Central",
    "San Lorenzo",
    "Talleres",
  ],
  "Primera Nacional": [
    "Agropecuario",
    "Almagro",
    "Almirante Brown",
    "Atlanta",
    "Brown de Adrogue",
    "Chacarita Juniors",
    "Deportivo Madryn",
    "Deportivo Moron",
    "Estudiantes Rio Cuarto",
    "Ferro Carril Oeste",
    "Gimnasia y Tiro",
    "Nueva Chicago",
    "Patronato",
    "Quilmes",
    "Racing Cordoba",
    "San Martin Tucuman",
    "San Miguel",
    "Temperley",
    "Tristan Suarez",
    "All Boys",
  ],
  MLS: [
    "Atlanta United",
    "Austin FC",
    "CF Montreal",
    "Charlotte FC",
    "Chicago Fire",
    "Colorado Rapids",
    "Columbus Crew",
    "DC United",
    "FC Cincinnati",
    "FC Dallas",
    "Houston Dynamo",
    "Inter Miami",
    "LA Galaxy",
    "Los Angeles FC",
    "Minnesota United",
    "Nashville SC",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City",
  ],
  "Liga MX": [
    "America",
    "Atlas",
    "Atletico San Luis",
    "Cruz Azul",
    "Guadalajara",
    "Juarez",
    "Leon",
    "Mazatlan",
    "Monterrey",
    "Necaxa",
    "Pachuca",
    "Puebla",
    "Pumas UNAM",
    "Queretaro",
    "Santos Laguna",
    "Tigres UANL",
    "Tijuana",
    "Toluca",
    "Club Leon",
    "Morelia",
  ],
  "Scottish Premiership": [
    "Aberdeen",
    "Celtic",
    "Dundee",
    "Dundee United",
    "Heart of Midlothian",
    "Hibernian",
    "Kilmarnock",
    "Motherwell",
    "Rangers",
    "Ross County",
    "St. Johnstone",
    "St. Mirren",
  ],
  "Scottish Championship": [
    "Airdrieonians",
    "Ayr United",
    "Dunfermline Athletic",
    "Falkirk",
    "Greenock Morton",
    "Hamilton Academical",
    "Livingston",
    "Partick Thistle",
    "Queen's Park",
    "Raith Rovers",
  ],
  "Saudi Pro League": [
    "Abha",
    "Al Akhdoud",
    "Al Ettifaq",
    "Al Fateh",
    "Al Feiha",
    "Al Hilal",
    "Al Ittihad",
    "Al Khaleej",
    "Al Nassr",
    "Al Raed",
    "Al Riyadh",
    "Al Shabab",
    "Al Taawoun",
    "Al Tai",
    "Al Wehda",
    "Al Ahli",
    "Al Qadsiah",
    "Damac",
    "Al Orobah",
    "Al Kholood",
  ],
  "J1 League": [
    "Albirex Niigata",
    "Avispa Fukuoka",
    "Cerezo Osaka",
    "FC Tokyo",
    "Gamba Osaka",
    "Kashima Antlers",
    "Kashiwa Reysol",
    "Kawasaki Frontale",
    "Kyoto Sanga",
    "Machida Zelvia",
    "Nagoya Grampus",
    "Sagan Tosu",
    "Sanfrecce Hiroshima",
    "Shonan Bellmare",
    "Tokyo Verdy",
    "Urawa Red Diamonds",
    "Vissel Kobe",
    "Yokohama F. Marinos",
    "Yokohama FC",
    "Jubilo Iwata",
  ],
  "J2 League": [
    "Blaublitz Akita",
    "Ehime FC",
    "Fagiano Okayama",
    "Fujieda MYFC",
    "Iwaki FC",
    "JEF United Chiba",
    "Mito HollyHock",
    "Montedio Yamagata",
    "Oita Trinita",
    "Renofa Yamaguchi",
    "Roasso Kumamoto",
    "Shimizu S-Pulse",
    "Thespakusatsu Gunma",
    "Tokushima Vortis",
    "Tochigi SC",
    "V-Varen Nagasaki",
    "Vegalta Sendai",
    "Ventforet Kofu",
    "Yokohama FC",
    "Kagoshima United",
  ],
  "K League 1": [
    "Daegu FC",
    "Daejeon Hana Citizen",
    "FC Seoul",
    "Gangwon FC",
    "Gimcheon Sangmu",
    "Gwangju FC",
    "Incheon United",
    "Jeju United",
    "Jeonbuk Hyundai Motors",
    "Pohang Steelers",
    "Suwon FC",
    "Ulsan HD",
    "Busan IPark",
    "Seongnam FC",
    "Anyang",
    "Bucheon FC",
    "Cheongju FC",
    "Gyeongnam FC",
    "Jeonnam Dragons",
    "Suwon Samsung Bluewings",
  ],
  "A-League": [
    "Adelaide United",
    "Auckland FC",
    "Brisbane Roar",
    "Central Coast Mariners",
    "Macarthur FC",
    "Melbourne City",
    "Melbourne Victory",
    "Newcastle Jets",
    "Perth Glory",
    "Sydney FC",
    "Wellington Phoenix",
    "Western Sydney Wanderers",
    "Western United",
    "Canberra United",
    "Gold Coast United",
    "North Queensland Fury",
    "South Melbourne",
    "Sydney Olympic",
    "Wollongong Wolves",
    "Adelaide City",
  ],
  "Danish Superliga": [
    "Aalborg",
    "AGF",
    "Brondby",
    "FC Copenhagen",
    "FC Midtjylland",
    "Lyngby",
    "Nordsjaelland",
    "Randers",
    "Silkeborg",
    "Sonderjyske",
    "Vejle",
    "Viborg",
  ],
  "Swiss Super League": [
    "Basel",
    "Grasshopper",
    "Lausanne-Sport",
    "Lugano",
    "Luzern",
    "Servette",
    "Sion",
    "St. Gallen",
    "Winterthur",
    "Young Boys",
    "Yverdon",
    "Zurich",
  ],
  "Austrian Bundesliga": [
    "Austria Klagenfurt",
    "Austria Vienna",
    "BW Linz",
    "Hartberg",
    "LASK",
    "Rapid Vienna",
    "Red Bull Salzburg",
    "Sturm Graz",
    "Tirol",
    "Wolfsberger AC",
    "Altach",
    "Grazer AK",
  ],
  "Greek Super League": [
    "AEK Athens",
    "Asteras Tripolis",
    "Atromitos",
    "Lamia",
    "OFI Crete",
    "Olympiacos",
    "Panathinaikos",
    "PAOK",
    "Aris",
    "Volos",
    "Panserraikos",
    "Kallithea",
    "Levadiakos",
    "AEL",
    "PAS Giannina",
    "Panetolikos",
    "Ionikos",
    "Apollon Smyrnis",
    "Ergotelis",
    "Xanthi",
  ],
  "Polish Ekstraklasa": [
    "Cracovia",
    "GKS Katowice",
    "Gornik Zabrze",
    "Jagiellonia Bialystok",
    "Korona Kielce",
    "Lech Poznan",
    "Legia Warsaw",
    "Lechia Gdansk",
    "Motor Lublin",
    "Piast Gliwice",
    "Pogon Szczecin",
    "Puszcza Niepolomice",
    "Radomiak Radom",
    "Rakow Czestochowa",
    "Slask Wroclaw",
    "Stal Mielec",
    "Widzew Lodz",
    "Zaglebie Lubin",
    "Arka Gdynia",
    "Wisla Krakow",
  ],
  "Czech First League": [
    "Banik Ostrava",
    "Bohemians 1905",
    "Ceske Budejovice",
    "Dukla Prague",
    "Hradec Kralove",
    "Jablonec",
    "Karvina",
    "Liberec",
    "Mlada Boleslav",
    "Olomouc",
    "Pardubice",
    "Plzen",
    "Slavia Prague",
    "Slovacko",
    "Sparta Prague",
    "Teplice",
    "Vyskov",
    "Brno",
    "Opava",
    "Zlin",
  ],
  "Ukrainian Premier League": [
    "Chornomorets Odesa",
    "Dynamo Kyiv",
    "Inhulets",
    "Karpaty Lviv",
    "Kolos Kovalivka",
    "Kryvbas Kryvyi Rih",
    "LNZ Cherkasy",
    "Obolon Kyiv",
    "Oleksandriya",
    "Polissya Zhytomyr",
    "Rukh Lviv",
    "Shakhtar Donetsk",
    "Veres Rivne",
    "Vorskla Poltava",
    "Zorya Luhansk",
    "Metalist 1925",
    "Dnipro-1",
    "Hoverla Uzhhorod",
    "Illichivets",
    "Sevastopol",
  ],
  "Romanian SuperLiga": [
    "CFR Cluj",
    "Dinamo Bucuresti",
    "Farul Constanta",
    "FCSB",
    "Hermannstadt",
    "Otelul Galati",
    "Petrolul Ploiesti",
    "Rapid Bucuresti",
    "Sepsi OSK",
    "Universitatea Cluj",
    "Universitatea Craiova",
    "UTA Arad",
    "Unirea Slobozia",
    "Botosani",
    "Politehnica Iasi",
    "Gloria Buzau",
    "Steaua Bucuresti",
    "Voluntari",
    "Astra Giurgiu",
    "Viitorul",
  ],
  "Serbian SuperLiga": [
    "Backa Topola",
    "Cukaricki",
    "Crvena zvezda",
    "IMT Belgrade",
    "Jedinstvo Ub",
    "Mladost Lucani",
    "Napredak",
    "Novi Pazar",
    "OFK Belgrade",
    "Partizan",
    "Radnicki 1923",
    "Radnicki Nis",
    "Spartak Subotica",
    "Tekstilac Odzaci",
    "Vojvodina",
    "Zeleznicar Pancevo",
    "Javor Ivanjica",
    "Indjija",
    "Metalac Gornji Milanovac",
    "Kolubara",
  ],
  "Croatian League": [
    "Dinamo Zagreb",
    "Hajduk Split",
    "Istra 1961",
    "Lokomotiva Zagreb",
    "Osijek",
    "Rijeka",
    "Sibenik",
    "Slaven Belupo",
    "Varazdin",
    "Gorica",
  ],
  "Norwegian Eliteserien": [
    "Bodo/Glimt",
    "Brann",
    "Fredrikstad",
    "HamKam",
    "Haugesund",
    "KFUM Oslo",
    "Kristiansund",
    "Lillestrom",
    "Molde",
    "Odd",
    "Rosenborg",
    "Sandefjord",
    "Sarpsborg 08",
    "Stromsgodset",
    "Tromso",
    "Viking",
    "Valerenga",
    "Aalesund",
    "Start",
    "Sogndal",
  ],
  "Swedish Allsvenskan": [
    "AIK",
    "Brommapojkarna",
    "Degerfors",
    "Djurgarden",
    "Elfsborg",
    "GAIS",
    "Goteborg",
    "Hacken",
    "Halmstad",
    "Hammarby",
    "IFK Norrkoping",
    "Kalmar",
    "Malmo",
    "Mjallby",
    "Sirius",
    "Varnamo",
    "Orebro",
    "Helsingborg",
    "Trelleborg",
    "Sundsvall",
  ],
  "Finnish Veikkausliiga": [
    "AC Oulu",
    "EIF",
    "Gnistan",
    "Haka",
    "HJK",
    "Ilves",
    "Inter Turku",
    "KuPS",
    "Lahti",
    "SJK",
    "VPS",
    "Mariehamn",
  ],
  "Chinese Super League": [
    "Beijing Guoan",
    "Cangzhou Mighty Lions",
    "Changchun Yatai",
    "Chengdu Rongcheng",
    "Henan",
    "Meizhou Hakka",
    "Nantong Zhiyun",
    "Qingdao Hainiu",
    "Qingdao West Coast",
    "Shanghai Port",
    "Shanghai Shenhua",
    "Shandong Taishan",
    "Shenzhen Peng City",
    "Tianjin Jinmen Tiger",
    "Wuhan Three Towns",
    "Zhejiang",
    "Guangzhou",
    "Dalian Pro",
    "Hebei",
    "Jiangsu",
  ],
  "Indian Super League": [
    "Bengaluru FC",
    "Chennaiyin FC",
    "East Bengal",
    "FC Goa",
    "Hyderabad FC",
    "Jamshedpur FC",
    "Kerala Blasters",
    "Mohun Bagan",
    "Mumbai City",
    "NorthEast United",
    "Odisha FC",
    "Punjab FC",
  ],
  "South African Premiership": [
    "AmaZulu",
    "Cape Town City",
    "Chippa United",
    "Golden Arrows",
    "Kaizer Chiefs",
    "Magesi FC",
    "Mamelodi Sundowns",
    "Marumo Gallants",
    "Orlando Pirates",
    "Polokwane City",
    "Richards Bay",
    "Sekhukhune United",
    "Stellenbosch",
    "SuperSport United",
    "TS Galaxy",
    "Royal AM",
    "Ajax Cape Town",
    "Bloemfontein Celtic",
    "Bidvest Wits",
    "Platinum Stars",
  ],
  "Egyptian Premier League": [
    "Al Ahly",
    "Al Ittihad Alexandria",
    "Al Masry",
    "Al Mokawloon",
    "Bank El Ahly",
    "Ceramica Cleopatra",
    "El Dakhleya",
    "El Gouna",
    "ENPPI",
    "Future FC",
    "Haras El Hodoud",
    "Ismaily",
    "National Bank",
    "Pyramids FC",
    "Smouha",
    "Talaea El Gaish",
    "Zamalek",
    "ZED FC",
    "Pharco",
    "Modern Sport",
  ],
  "Moroccan Botola": [
    "FUS Rabat",
    "Hassania Agadir",
    "Ittihad Tanger",
    "JS Soualem",
    "Moghreb Tetouan",
    "Olympic Safi",
    "Raja Casablanca",
    "Renaissance Berkane",
    "Renaissance Zemamra",
    "Wydad Casablanca",
    "AS FAR",
    "Difaa El Jadida",
    "Kawkab Marrakech",
    "Mouloudia Oujda",
    "Racing Casablanca",
    "Youssoufia Berrechid",
    "KAC Kenitra",
    "Maghreb Fez",
    "Chabab Mohammedia",
    "SCCM Mohammedia",
  ],
  "Colombian Primera A": [
    "Aguilas Doradas",
    "Alianza FC",
    "America de Cali",
    "Atletico Bucaramanga",
    "Atletico Nacional",
    "Boyaca Chico",
    "Deportes Tolima",
    "Deportivo Cali",
    "Deportivo Pasto",
    "Envigado",
    "Fortaleza CEIF",
    "Independiente Medellin",
    "Independiente Santa Fe",
    "Jaguares de Cordoba",
    "Junior",
    "La Equidad",
    "Millonarios",
    "Once Caldas",
    "Patriotas",
    "Pereira",
  ],
  "Chilean Primera Division": [
    "Audax Italiano",
    "Cobresal",
    "Colo-Colo",
    "Coquimbo Unido",
    "Cobreloa",
    "Deportes Iquique",
    "Everton de Vina del Mar",
    "Huachipato",
    "Nublense",
    "O'Higgins",
    "Palestino",
    "Universidad Catolica",
    "Universidad de Chile",
    "Union Espanola",
    "Union La Calera",
    "Deportes Copiapo",
    "Santiago Wanderers",
    "Magallanes",
    "Curico Unido",
    "Antofagasta",
  ],
  "Peruvian Liga 1": [
    "ADT",
    "Alianza Atletico",
    "Alianza Lima",
    "Atletico Grau",
    "Carlos A. Mannucci",
    "Cienciano",
    "Comerciantes Unidos",
    "Cusco FC",
    "Deportivo Garcilaso",
    "FBC Melgar",
    "Los Chankas",
    "Sport Boys",
    "Sport Huancayo",
    "Sporting Cristal",
    "Universitario",
    "Union Comercio",
    "UTC",
    "Cesar Vallejo",
    "Binacional",
    "Ayacucho FC",
  ],
};

const getClubName = (league: LeagueSeed, index: number) => `${league.name} Club ${index + 1}`;

const getClubNamesForLeague = (league: LeagueSeed, clubCount: number) => {
  const names = realClubNamesByLeague[league.name] ?? [];
  return Array.from({ length: clubCount }, (_, index) => names[index] ?? getClubName(league, index));
};

const tacticalStyles: ClubSeed["tacticalStyle"][] = ["balanced", "pressing", "counter", "possession"];

const getClubStats = (league: LeagueSeed, index: number, clubCount: number) => {
  const normalizedRank = clubCount <= 1 ? 0 : index / (clubCount - 1);
  const reputation = Math.max(40, Math.round(league.reputation + 8 - normalizedRank * 20));
  const managerQuality = Math.max(45, Math.min(95, reputation + 2 - Math.round(normalizedRank * 6)));
  const financeBalance = Math.round((reputation ** 2) * 22000);
  const tacticalStyle = tacticalStyles[index % tacticalStyles.length] ?? "balanced";

  return { reputation, managerQuality, financeBalance, tacticalStyle };
};

const buildPlayers = (clubName: string, country: string): PlayerSeed[] => {
  return Array.from({ length: 25 }, (_, index) => {
    const playerNumber = index + 1;
    const preferredPosition =
      playerNumber <= 2 ? "GK" : playerNumber <= 8 ? "DEF" : playerNumber <= 16 ? "MID" : "ATT";

    return {
      name: `${clubName} Player ${playerNumber}`,
      age: 18 + ((playerNumber * 3 + clubName.length) % 17),
      nationality: country,
      preferredPosition,
    };
  });
};

export const clubsByLeague: Record<string, ClubSeed[]> = topLeagues.reduce(
  (accumulator, league) => {
    const key = getLeagueKey(league);
    const clubCount = clubCountByLeague[league.name] ?? defaultClubCount;

    const clubs = getClubNamesForLeague(league, clubCount).map((name, index) => {
      const stats = getClubStats(league, index, clubCount);
      return {
        name,
        leagueName: league.name,
        country: league.country,
        ...stats,
        players: buildPlayers(name, league.country),
      };
    });

    accumulator[key] = clubs;
    return accumulator;
  },
  {} as Record<string, ClubSeed[]>,
);
